name: app_ui
description: App UI Component Library
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  material_color_utilities: '>=0.8.0 <=0.11.1'
  google_fonts: ^6.2.1

dev_dependencies:
  build_runner: ^2.0.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter

